title: Daniel Wu
description: Professional Portfolio
email: daniel.wu05@outlook.com
url: "https://danielw21.github.io/Personal-Portfolio/" 
theme: minima

github_username: GitHub
linkedin_username: LinkedIn

minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/DanielW21
    - platform: linkedin
      user_url: https://www.linkedin.com/in/daniel-wu-8436b7277/

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Theme settings
plugins:
  # - jekyll-feed
  - jekyll-seo-tag

permalink: pretty
